# Aspectos básicos

All chapters start with a first-level heading followed by your chapter title, like the line above. There should be only one first-level heading (`#`) per .Rmd file.

## Uso del do-file editor

## Uso del comando Help

# Empezando a programar

## Carga y análisis descriptivo de datos

En Stata podemos cargar datos internos y externos. Los primeros podemos llamarlos a través del comando `help dta_examples`. Al ejecutar este comando, veremos que dispondremos de más de 25 conjuntos de datos los cuales podemos llamar usando el comando `sysuse`. Para los datos externos de formato .dta usaremos el comando `use`, mientras que para otros formatos como .csv, .xls, .xlsx, .dbf, entre otros; se usará el comando `import`.    

### Datos internos

Para este ejemplo, usaremos el conjunto de datos interno "auto" seguido de la opción `clear` ya que nos permite limpiar la memoria de cualquier otro dataset usado previamente. Seguido de ello, usaremos el comando `describe` para que Stata nos brinde una descripción general de dicho dataset.

```{r, include=FALSE}
library(Statamarkdown)
statapath <- "D:/OneDrive - Superintendencia Nacional de Servicios de Saneamiento/Escritorio/Stata16/StataMP-64.exe"
knitr::opts_chunk$set(engine.path=list(stata=statapath))
```

```{stata}
sysuse auto, clear
describe
```

Inmediatamente Stata nos informa que la data esta relacionada con datos asociados a automóviles del año 1978, la cual exhibe 74 observaciones con 12 variables que, al hacer una lectura rápida de la columna de etiquetas de la variable (variable label), están vinculadas a las características físicas de los vehículos tales como: el peso (weight) y el largo (length), así como el espacio de la maletera (trunk) y el espacio libre (headroom). Asimismo, existen variables asociadas al precio (price), millas recorridas por galón (mpg), entre otras. Finalmente, es importante resaltar que de las 12 variables, 11 de ellas son de tipo numérico y solo 1 de tipo texto o cadena. 

Para seguir conociendo este dataset, ahora usaremos el comando `summarize` con la finalidad de que Stata nos muestre los principales estadísticos descriptivos de la data.

```{stata, results='hide'}
summarize
```

```{stata, echo=FALSE}
sysuse auto, clear
summarize
```

La tabla nos muestra estadísticos descriptivos básicos como la media, desviación estándar y los valores mínimos y máximos. Como se observa, estos estadísticos son aplicables solo a variables numéricas, por esa razón el contenido de la tabla para la variable marca (make) esta vacía. Asimismo, podemos utilizar la opción del comando `summarize` denominado `detail` para obtener información estadística adicional como la varianza, el sesgo y la kurtosis, así como una serie de percentiles que nos permitirán realizar un análisis descriptivo más detallado. Empleemos este comando con la variable precio (price):

```{stata, results='hide'}
summarize price, detail
```

```{stata, echo=FALSE}
sysuse auto, clear
summarize price, detail
```

Otro comando que usaremos frecuentemente es el comando `codebook` ya que nos permitirá obtener información complementaria a la antes vista, esta vez sin importar si la variable es número o texto. Utilicemos este comando para la variable de tipo texto llamada marca (make).

```{stata, results='hide'}
codebook make
```

```{stata, echo=FALSE}
sysuse auto, clear
codebook make
```

Como acabamos de ver, el comando `codebook` nos muestra información muy importante para cualquier analista de datos, en particular, sobre los valores únicos (unique values) y valores pérdidos (missing values). En este caso, Stata nos señala que la variable marca (make) tiene 74 valores único y 0/74 missings values. Esto último significa que los autos de la muestra los componen 74 autos de marcas diferentes, de los cuales para el 100% de la muestra se encuentra dicha información.

### Datos externos

Stata puede importar sin ningún problema datos en formato .dta; para cuáles son las posibilidades que tenemos para importar archivos debemos escribir el comando `help import`. La ventana que muestra el Stata permite observar todos los formatos compatibles a importar, por lo que solo bastaría tener claridad de que tipo de formato queremos importar para acceder a la sintaxis y empezar a cargar nuestros datos. Aquí un ejemplo para importar archivos de formato excel.

```{stata, results='hide'}
import excel "ruta del archivo.xlsx", firstrow sheet("Sheet1") clear
```

En el término "ruta del archivo.xlsx" del código debemos ingresar la ruta en la cual tenemos nuestro archivo .xlsx que deseamos importar al Stata. Por su parte, la opción "firstrow" señala al Stata que la primera fila de nuestro archivo excel debe ser considerada como la lista de variables. Finalmente, "sheet()" es una opción para especificar la hoja del libro excel, lo que es sumamente importante cuando manejamos varias hojas dentro de un mismo libro. 

Una vez importado el archivo, podemos iniciar nuestro análisis descriptivo que vimos en la sección anterior.

## Tipo de variables y formatos

Profundicemos un poco sobre las variables y formatos ya que son parte fundamental en la gestión de datos. Afortunadamente, en Stata trabajaremos con solo variables de clase númerica y texto por lo que no será muy complejo abordar esta sección.

### Tipos de almacenamiento

Las variables numéricas y se almacenará en la memoria a través de diferentes tipologías. Comenzando por las variables numéricas tenemos los siguientes tipos de almacenamiento: byte, int, long, float y double.

Cada tipología esta directamente relacionado con su tamaño de almacenamiento en términos de "bytes". Así, una variable númerica de tipo "byte" tendrá un peso de 1 "bytes" en la memoria, de modo que este tipo de variable estará usualmente asociada con números de hasta 3 caracteres. 

Al escribir el comando `help Data types` podemos observar todas las tipologías tanto para las variables numéricas y texto, las cuales siguen la misma lógica del párrafo anterior.

## Principales comandos
