# Gestión de datos con ENAHO

You can add parts to organize one or more book chapters together. Parts can be inserted at the top of an .Rmd file, before the first-level chapter heading in that same file. 

Add a numbered part: `# (PART) Act one {-}` (followed by `# A chapter`)

Add an unnumbered part: `# (PART\*) Act one {-}` (followed by `# A chapter`)

Add an appendix as a special kind of un-numbered part: `# (APPENDIX) Other stuff {-}` (followed by `# A chapter`). Chapters in an appendix are prepended with letters instead of numbers.

## Gestión del módulo 100

El módulo 100 corresponde al módulo de las "Características de la Vivienda y del Hogar" por lo que inmediatamente iniciamos la programación abriendo el archivo formato .dta denominado "enaho01-2022-100".

```{stata, results='hide'}
cd "ruta del archivo"
use enaho01-2022-100, clear
```

Ahora bien, empezaremos con las variables identificadoras; estas son las variables conglome, vivienda y hogar las cuales describiremos a continuación:

```{stata, results='hide'}
describe conglome vivienda hogar
```

```{stata, echo=FALSE}
cd "D:\OneDrive - Superintendencia Nacional de Servicios de Saneamiento\Escritorio\renzo\asesorías\Noemy\data"
use enaho01-2022-100, clear
describe conglome vivienda hogar
```

El resultado anterior nos muestra que las variables identificadoras son de tipo texto, de 2 a 6 caracteres, que refieren al número de conglomerado, número de selección de la vivienda y número secuencial del hogar. Finalmente, empleados un `codebook` para observar lo valores únicos y los missings values.

```{stata, results='hide'}
codebook conglome vivienda hogar
```

```{stata, echo=FALSE}
cd "D:\OneDrive - Superintendencia Nacional de Servicios de Saneamiento\Escritorio\renzo\asesorías\Noemy\data"
use enaho01-2022-100, clear
codebook conglome vivienda hogar
```

Como observamos, los tres identificadores están presentes para las 44,122 observaciones lo que sugiere que todos las viviendas se encuentran identificadas. Asimismo, existen 5,359 valores únicos de conglomerados; esto nos indica que las 44,122 viviendas de la muestra han sido seleccionadas de tal modo que pertecen a alguno de los 5,359 conglomerados, 649 viviendas y cuentan con algún número secuencial del hogar asignado.

En tal sentido, las variables "conglome", "vivienda" y "hogar" serán una suerte de "documento de identidad" que nos permitirá individualizar a las viviendas. Con la finalidad de efectuar esto último, usamos la función `group()` del comando `egen`, en la que crearemos una variable denominada "id".

```{stata, results='hide'}
egen id = group(conglome vivienda hogar)
```

Luego, corroboramos que esta variable se encuentre dispersa en toda la muestra y que, además, sean valores únicos, por lo que usaremos las funciones `count`.

```{stata, results='hide'}
count if id
```

```{stata, echo=FALSE}
cd "D:\OneDrive - Superintendencia Nacional de Servicios de Saneamiento\Escritorio\renzo\asesorías\Noemy\data"
use enaho01-2022-100, clear
egen id = group(conglome vivienda hogar)
count if id
```

## Gestión del módulo 200

## Gestión del módulo 300

## Gestión del módulo 400

## Gestión del módulo 500

## Integrando módulos
